automate asc for iot and sentinel
Azure/azure-iiot-services pull request #11
Opened 2019-06-26 06:18 UTC by Auguzt

2019-06-26 06:31 UTC, marcschier approved these changes

2019-06-26 06:31 UTC, marcschier commented on deploy/automate-asc.ps1
> +{
Consisten curly braces, i think same line is good

2019-06-28 10:14 UTC, marcschier requested changes
Could you also add this to the other deployments?

2019-06-28 10:14 UTC, marcschier commented on deploy/local/template.json
> +		"workspaceName": {
Spaces instead of tabs

2019-06-28 10:14 UTC, marcschier commented on deploy/local/template.json
> +		"workspace-name": {
Spaces instead of tabs.

2019-06-28 13:50 UTC, Auguzt commented
Script for automating asc for iot, workspace creation and sentinel. Documentation to enable asc for iot and sentinel is added in separate PR.

2019-06-28 13:51 UTC, merged